Market.Web/ViewModels/ProductViewModels.cs
using Market.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Market.Web.ViewModels
{
    public class ProductSearchViewModel
    {
        public List<Product> Products { get; set; }
        public int pageNo { get; set; }
        public string SearchTerm { get; set; }
        public Pager Pager { get; set; }
    }
    public class EditProductModel
        {
            public int ID { get; set; }

            public string Name { get; set; }
            public string Description { get; set; }
            public decimal Price { get; set; }
            public int CategoryID { get; set; }
            public string ImageUrl { get; set; }

            public List<Category> AvailableCategories { get; set; }
        }

    public class NewProductViewModel
    {
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Price { get; set; }
        public int CategoryID { get; set; }
        public string ImageURL { get; set; }

        public List<Category> AvailableCategories { get; set; }
    }


    public class ProductViewModel
    {
        public Product Product { get; set; }
     
    }
}

Market.Web/Controllers/ProductController.cs
using Market.Entities;
using Market.Services;
using Market.Web.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace Market.Web.Controllers
{
    public class ProductController : Controller
    {

        //ProductsService productsService = new ProductsService();
       // CategorysServices CategorysServices = new CategorysServices();

        public ActionResult Index()
        {

            return PartialView();
        }

        public ActionResult ProductTable(string search, int? pageNo)
        {

            ProductSearchViewModel model = new ProductSearchViewModel();

            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value>0 ? pageNo.Value : 1 :1;
            //            simmilar to above single line
            //            if (pageNo.HasValue)
            //            { if(pageNo.Value>0)
            //                {
            //                    model.pageNo = pageNo.Value;
            //                }
            //                else
            //                {
            //                    model.pageNo = 1
            //;                }
            //            }
            //            else { model.pageNo = 1; }

            // model.Products = ProductsService.Instance.GetProducts(model.pageNo);

            var totalRecord = ProductsService.Instance.GetProductsCount(search);
            model.Products = ProductsService.Instance.GetProducts(search, pageNo.Value);

            if (model.Products != null)
            {
                int pageSize = ConfigurationService.Instance.PagesizeConfiguration();
                model.Pager = new Pager(totalRecord, pageNo, pageSize);
                return PartialView("ProductTable", model);
            }
            else
            {
                return HttpNotFound();
            }

            //   products = products.Where(p => p.Name == search).ToList();
            //if (!string.IsNullOrEmpty(search))
            //{
            //    model.SearchTerm = search;
            //   model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            //}
            // return PartialView(model);
        }

        //Create 
        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories= CategorysServices.Instance.GetAllCategories();

            return PartialView(model);
        }


        [HttpPost]
        public ActionResult Create(NewProductViewModel model) // Creating new Product
        {
            if (ModelState.IsValid)
            {
                var newProduct = new Product()
                {
                    Name = model.Name,
                    Description = model.Description,
                    Price = model.Price,
                    ImageUrl = model.ImageURL,
                    //CategoryID=model.CategoryID
                    Category = CategorysServices.Instance.GetCategory(model.CategoryID)
                };
                ProductsService.Instance.saveProduct(newProduct);
                return RedirectToAction("ProductTable");
            }
            else
            {
                return PartialView(model);
            }
        
        }
        //Edit
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductModel model = new EditProductModel();

            var product = ProductsService.Instance.GetProduct(ID);
            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageUrl = product.ImageUrl;

            model.AvailableCategories = CategorysServices.Instance.GetAllCategories();


            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductModel model) // taking value from view in Product object 
        {
            var existingProduct = ProductsService.Instance.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;
         

            existingProduct.Category = null; //mark it null. Because the referncy key is changed below
            existingProduct.CategoryID = model.CategoryID;

            // dont update imageURL if its empty
            if (!string.IsNullOrEmpty(model.ImageUrl))
            {
                existingProduct.ImageUrl = model.ImageUrl;
            }

            //ProductsService.Instance.UpdateProduct(existingProduct);



            ProductsService.Instance.updateProduct(existingProduct); // now passing Product value to USER-DEFINED Function which is created in Market Product class. 
            return RedirectToAction("ProductTable");
        }
        [HttpPost]
        public ActionResult Delete(int ID) // taking value from view in Product object 
        {
            ProductsService.Instance.DeleteProduct(ID); // now passing Product value to USER-DEFINED Function which is created in Market Product class. 
            return RedirectToAction("ProductTable");
        }


        [HttpGet]
        public ActionResult ProductDetails(int ID )
        {
            ProductViewModel model = new ProductViewModel();

            model.Product = ProductsService.Instance.GetProduct(ID);

            return View(model);
        }

    }

}

Market.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.Web.Controllers
{
    public class SharedController : Controller
    {
       //Image uploading 

        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

            try
            {
                var file = Request.Files[0];

                var filename =Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/Images/"), filename);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/Content/Images/{0}",filename) };

                //  var newImage = new Image() { name = filename };

               
            }
            catch(Exception ex)
            {
                result.Data = new { success = false , Message = ex.Message  };
            }

            return result;
                      
        }
    }
}

Market.Web/Views/Product/Create.cshtml
@model NewProductViewModel
@{
    ViewBag.Title = "Create Product";
    
   var imageurl = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/Images/system/placeholder.png";
    
}

<h2>Create Product</h2>



<form id="createProduct">



    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <lable>Category<span class="text-danger">*</span></lable>
                <select class="form-control" name="CategoryID">
                    @foreach (var Category in Model.AvailableCategories)
                    {
                        <option value="@Category.ID">@Category.Name</option>
                    }
                </select>
            </div>

            <div class="form-group">
                <lable class="form-group">Name<span class="text-danger">*</span></lable>
                <input class="form-control" name="Name" />

            </div>

            <div class="form-group">

                <lable>Description</lable>
                <input class="form-control" name="Description" />

            </div>


            <div class="form-group">

                <lable>Price<span class="text-danger">*</span></lable>
                <input class="form-control" name="Price" />

            </div>


            <div class="form-group">
                <lable>Image<span class="text-danger">*</span></lable>
                <input id="ImageUrl" type="hidden" name="ImageUrl" />
                <input id="imageUpload" name="Image" type="file" accept=".png,.jpg" />
                <br />
            </div>



            @*<div class="form-group">
                <lable>Is Featured?</lable>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input type="radio" name="isfeatured" value="true" /> true</label>
                    </div>
                    <div class="radio form-control">
                        <label><input type="radio" name="isfeatured" value="false" /> False</label>
                    </div>
                </div>
                @*<input class="form-control" type="radio" name="isfeatured" value="true" /> true
                    <input class="form-control" type="radio" name="isfeatured" value="false" /> False


            </div>*@


            <button id="saveBtn" type="button" class="btn btn-primary"> Save Product</button>
            <button id="cancleBtn"  class="btn btn-danger" type="button">Cancle</button>
        </div>

        <div class="col-md-4">

            <div class="thumb">
                <img src="@imageurl" id="Productimage"  class="img-thumbnail img-fluid"  />
            </div>
        </div>

    </div>

</form>


<script>

    $("#cancleBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer")
    });


    
    $('#imageUpload').change(function () {
        debugger;

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: "POST",
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {
                debugger;
                console.log(response)
                if (response.Success) {
                    $('#ImageUrl').val(response.ImageURL)
                    $('#Productimage').attr("src", response.ImageURL)
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });


    });


    $("#saveBtn").click(function () {

        if ($("#createProduct").valid()) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Create","Product")', //'/Product/Create',
                data: $('#createProduct').serialize()
            })
                .done(function (response) {
                    $("#tableContainer").html(response);
                    $("#actionContainer").html("");
                    focusAction("tableContainer")
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Fail");
                });
        }
        else {
            {
                swal({
                    title: " JQury Warning..!!",
                    text: "Please enter all Required Data fields",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                });
            }
        }
     
    });




    $("#createProduct").validate({
        // Specify validation rules
        rules: {
            // The key name on the left side is the name attribute
            // of an input field. Validation rules are defined
            // on the right side   
            Name: { required: true, minlength: 5, maxlength: 50 },
            Description: { maxlength: 500 },
            Price: { range : [1,100000]}, //{ required: true, minlength: 1, maxlength: 7 },
            Image: { required: true },
        },
        // Specify validation error messages
        messages: {
            Name: { required: 'Name is Required', minlength: 'Minimum length is 5', maxlength: 'Maximun length is 50' },
            Description: { maxlength: 'Maximun length is 500' },
            Price: { required: 'Price is Required', minlength: 'Minimum Price is 1', maxlength: 'Maximun Price is 999999' },
            Image: { required: 'Product Image is required'},
        },

    });
</script>

Market.Web/Views/Product/Edit.cshtml
@*This is Product Create View*@

@model Market.Web.ViewModels.EditProductModel

@{
    ViewBag.Title = "Edit Product";

    var imageurl = !string.IsNullOrEmpty(Model.ImageUrl) ? Model.ImageUrl : "/Content/Images/system/placeholder.png";

}

<h2>Edit Product</h2>
<form id="EditProduct">

    <input type="hidden" name="ID" value="@Model.ID" />
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label>Category</label>
                <select class="form-group" name="CategoryId">
                    @foreach (var category in Model.AvailableCategories)
                    {
                        var selected = category.ID == Model.CategoryID ? "Selected" : string.Empty;
                        <option value="@category.ID" @selected>@category.Name </option>
                    }
                </select>
            </div>
            <div class="form-group">
                <lable class="form-group">Name</lable>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>

            <div class="form-group">
                <lable>Description</lable>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>
            <div class="form-group">
                <lable>Price</lable>
                <input class="form-control" name="Price" value="@Model.Price" />
            </div>

            <div class="form-group">
                <lable>Image</lable>
                <input id="ImageUrl" type="hidden" name="ImageUrl" value="@Model.ImageUrl" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png,.jpg" />
                <br />
            </div>

            <div class="form-group">
                <button id="updateBtn" type="button">Update Product</button>
                <button id="cancleBtn" type="button">cancle</button>

            </div>

        </div>


        <div class="col-md-4">

            <div class="thumb">
                <img src="@imageurl" class="img-thumbnail img-fluid" id="ProductImage" />
            </div>
        </div>


    </div>


</form>



<script>
    $("#cancleBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer")
    });

    $('#imageUpload').change(function () {

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: "POST",
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {

                console.log(response)
                if (response.Success) {
                    $('#ImageUrl').val(response.ImageURL)
                    $('#ProductImage').attr("src", response.ImageURL)
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });


    $("#updateBtn").click(function () {



        
        if ($("#EditProduct").valid()) {
            $.ajax({
                type: "POST",
                url: '@Url.Action("Edit", "Product")', //'/Product/Create',
                data: $('#EditProduct').serialize()
            })
                .done(function (response) {
                    $("#tableContainer").html(response);
                    $("#actionContainer").html("");
                    focusAction("tableContainer")
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Fail");
                });
        }
        else {
            {
                swal({
                    title: " JQury Warning..!!",
                    text: "Please enter all Required Data fields",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                });
            }
        }
     


        @*$.ajax({
            type: "POST",
            url: '@Url.Action("Edit", "Product")', //'/Product/Edit',
            data: $('#EditProduct').serialize()
        })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#actionContainer").html("");
                focusAction("tableContainer")
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });*@
    });


    $("#EditProduct").validate({
        // Specify validation rules
        rules: {
            // The key name on the left side is the name attribute
            // of an input field. Validation rules are defined
            // on the right side   
            Name: { required: true, minlength: 5, maxlength: 50 },
            Description: { maxlength: 500 },
            Price: { range: [1, 100000] }, //{ required: true, minlength: 1, maxlength: 7 },
            
        },
        // Specify validation error messages
        messages: {
            Name: { required: 'Name is Required', minlength: 'Minimum length is 5', maxlength: 'Maximun length is 50' },
            Description: { maxlength: 'Maximun length is 500' },
            Price: { required: 'Price is Required', minlength: 'Minimum Price is 1', maxlength: 'Maximun Price is 999999' },
            
        },

    });
</script>

Market.Web/Views/Product/Index.cshtml
@{
    ViewBag.Title = "product Index";
}

<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        Products
                    </h2>
                </div><!-- /.title-section -->
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section><!-- /.flat-row -->


<div class="container">
    <div id="tableContainer">
        @{
            Html.RenderAction("ProductTable");

            //Html.RenderAction("Create");
        }
    </div>
    <hr />
    <div id="actionContainer">

    </div>
</div>


<script>
        function focusAction(controlToFocus) {
            $('html, body').animate({
                scrollTop: $("#" + controlToFocus).offset().top - 100
            }, 1000);
        }
</script>

Market.Web/Views/Product/ProductTable.cshtml
@model ProductSearchViewModel
@{
    ViewBag.Title = "Product Table";

}

@*<!-- Bootstrap  --> DAtaTable
<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css">
<!-- JavaScrip  -->
<script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>*@

<div>

    @*<h3>Products<span>( @Model.Products.Count )</span></h3>*@
    <br />
    <form>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <input class="form-control" id="searchtxt" name="Search" value="@Model.SearchTerm" placeholder="Search Products Here !!" />
                </div>
            </div>
            <div class="col-md-6">
                <button type="button" id="searchBtn" class="btn btn-primary">Search</button>
                <button type="button" id="resetBtn" class="btn btn-success ">Reset Search</button>
                <button type="button" id="newBtn" class="btn btn-warning">Create New Product</button>
            </div>

        </div>


    </form>
</div>

<div>
    <table id="ProductsTable" class="table" >
        <thead class="font-weight-bold">
            <tr>
                <th class="font-weight-bold"> Prodcuts Name (@Model.Pager.TotalItems)</th>
                <th class="font-weight-bold">Product Category</th>
                <th class="font-weight-bold">Price</th>
                <th class="font-weight-bold">Actions</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Products != null && Model.Products.Count > 0)
            {
                foreach (var product in Model.Products)
                {
                    <tr>
                        <td>@product.Name</td>
                        <td>
                            @if (product.Category != null)
                            {
                                <text>@product.Category.Name</text>
                            }
                            else
                            {
                                <text></text>
                            }
                        </td>
                        <td>@product.Price</td>
                        <td>
                            <button class="editBtn" data-id="@product.ID">Edit</button>

                            <button class="deleteBtn" data-id="@product.ID">Delete</button>

                            @*<button class="addtocart" data-id="@product.ID">add to cart</button>*@
                        </td>
                    </tr>
                }
            }
            else
            {
          
                <tr>
                    <td class="text-danger" colspan="4">
                 
                        No Product Found
                    </td>
                </tr>
            }


        </tbody>
    </table>
    <div>
        @if (Model.Pager != null && Model.Pager.TotalPages > 1)
        {


            if (Model.Pager.CurrentPage > 1)
            {
                <button class="pageButtons" data-pageNo="1"> First </button>
                <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage - 1)"> Previous </button>
            }
            for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <button class=" @activeClass pageButtons" data-pageNo="@page"> @page </button>
            }
            if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage + 1)"> next </button>
                <button class="pageButtons" data-pageNo="@Model.Pager.EndPage"> Last </button>
            }





        }
   


    </div>
</div>


<script>
    //$(document).ready(function () {
    //    $('#myTable').DataTable();
    //});
   // $('#ProductsTable').DataTable(); 

    $(".pageButtons").click(function () {
        $.ajax({
            type: "GET",
            url: '@Url.Action("ProductTable", "Product")', //'/Product/ProductTable',
            data: {
                pageNo: $(this).attr("data-pageno"),
                search: '@Model.SearchTerm'

            }
        })
            .done(function (response) {
                $("#actionContainer").html("");
                focusAction("tableContainer");
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });





    $("#searchBtn").click(function () {
        var seacrhvalue = $("#searchtxt").val();

        $.ajax({
            type: "GET",
            url: '@Url.Action("ProductTable", "Product")', //'/Product/ProductTable',
            data: { search: seacrhvalue }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });



    $("#resetBtn").click(function () {
        var seacrhvalue = $("#searchtxt").val();

        $.ajax({
            type: "GET",
            url: '@Url.Action("ProductTable", "Product")', //'/Product/ProductTable',

        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    /*'/Product/Create'*/

    $("#newBtn").click(function () {
      
        $.ajax({
            type: "GET",
            url: '@Url.Action("Create","Product")',
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction("actionContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });



    $(".editBtn").click(function () {

        $.ajax({
            type: "GET",
            url: '@Url.Action("Edit", "Product")', // '/Product/Edit',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                $("#actionContainer").html(response);
                focusAction("actionContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });
     


    $(".deleteBtn").click(function () {

        swal({
            title: "Confirm?",
            text: "Once deleted, you will not be able to recover this Product !!",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "Product")', //'/Product/Delete',
                        data: {
                            ID: $(this).attr('data-id')
                        }

                    })
                    .done(function (response) {
                       $("#tableContainer").html(response);
                       $("#actionContainer").html("");
                        focusAction("tableContainer");
                        })
                        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                            alert("Fail");
                        });
                    swal("Product Record Deleted Successfully", {
                        icon: "success",
                    });

                }
            });

        //debugger;

        //var confirmDelete = confirm("Are you sure you want to delete it ?");
        //if (confirmDelete) {
        //    $.ajax({
        //        type: "POST",
        //        url: '/Product/Delete',
        //        data: {
        //            ID: $(this).attr('data-id')
        //        }

        //    })
        //        .done(function (response) {
        //            $("#tableContainer").html(response);
        //        })
        //        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        //            alert("Fail");
        //        });
        //}

    });



    //var products = [];
    //$(".addtocart").click(function () {
    //    debugger;
    //    var productID = $(this).attr("data-id");
    //    products.push(productID);
    //    $.cookie('cartProducts', products.join('-'), { path: '/' });
    //    debugger;
    //    swal("Done", "Product Added To Cart!", "success");
    //});

</script>