Market.Web/ViewModels/OrdersViewModels.cs
using Market.Entities;
using Market.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Market.Web.ViewModels
{
    public class OrderViewModels
    {

        public List<Order> Orders { get; set; }
        public string userID { get; set; }
        public Pager Pager { get;  set; }
        public object status { get;  set; }
    }
    public class OrderDetailsViewModels
    {

        public Order Order { get; set; }
        public MarketUser OrderedBy { get; set; }
        public List<string> AvilableStatuses { get;  set; }
    }
}

Market.Web/Controllers/AdminController.cs
using Market.Services;
using Market.Web.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.Web.Controllers
{
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            AdminViewModel model = new AdminViewModel();
            model.CategoryCount = CategorysServices.Instance.GetCategoriesCount("");
            model.ProductCount = ProductsService.Instance.GetProductsCount("");
            model.ConfigurationCount = ConfigurationService.Instance.GetConfigurationCount();
            model.ToalordersCount = OrdersService.Instance.SearchOrdersCount("", "");
            return View(model);
        }
        // GET: Admin
        public ActionResult Category()
        {
            return View();
        }
        public ActionResult Products()
        {
              return View();
        }
        public ActionResult Configurations()
        {
            return View();
        }
        public ActionResult Orders()
        {
            return View();
        }
    }
}

Market.Web/Controllers/OrderController.cs
using Market.Services;
using Market.Web.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.Web.Controllers
{
    public class OrderController : Controller
    {

        private MarketSignInManager _signInManager;
        private MarketUserManager _userManager;


        public MarketSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<MarketSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public MarketUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<MarketUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }



        public ActionResult Index()
        {
            return PartialView("_Index");
        }


        // GET: Order
        public ActionResult OrderTable(string userID, string status, int? pageNo)
        {
            OrderViewModels model = new OrderViewModels();
            int pageSize = ConfigurationService.Instance.PagesizeConfiguration();
            model.userID = userID;
            model.status = status;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;

            model.Orders = OrdersService.Instance.SearchOrders(userID, status, pageNo.Value, pageSize);
            var totalRecord = OrdersService.Instance.SearchOrdersCount(userID, status);

            if (model.Orders != null)
            {

                model.Pager = new Pager(totalRecord, pageNo, pageSize);
                return PartialView("_OrderList", model);
            }
            else
            {
                return HttpNotFound();
            }
        }



        public ActionResult Details(int ID)
        {
            OrderDetailsViewModels model = new OrderDetailsViewModels();


            model.Order = OrdersService.Instance.GetOrderById(ID);
            if (model.Order != null)
            {
                model.OrderedBy = UserManager.FindById(model.Order.UserID);

            }
            model.AvilableStatuses = new List<string>() { "Pending", "In Progress", "Develered" };
            return PartialView("_Details", model);
        }

        public JsonResult ChangeStatus(string status, int ID)
        {

            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;

            result.Data = new { Success = OrdersService.Instance.UpdateOrderStatus(ID,status) };

            return result;

        }
    }
}

Market.Web/Views/Order/_Details.cshtml
@model  OrderDetailsViewModels

<div class="row">

    <div class="col-md-12">
        <div class="title-section">
            <h2 class="title">
                <br />
                @Model.OrderedBy.Name Order Detail
            </h2>
        </div><!-- /.title-section -->
    </div><!-- /.col-md-12 -->

</div><!-- /.row -->




@if (Model != null && Model.Order != null)
{

    var i = 1;
    <section class="flat-row main-shop shop-slidebar" style="    padding: 0px 29px 0px;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 order-md-2 mb-4">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-muted"><b><h3>Shooping Cart</h3></b></span>
                    </h4>

                    <ul class="list-group mb-3">

                        @foreach (var orderItem in Model.Order.OrderItems)
                        {
                            //var productQuantity = Model.CartProductIDs.Where(productid => productid == product.ID).Count();

                            <li class="list-group-item d-flex justify-content-between lh-condensed" data-id="@orderItem.ID">
                                <div>
                                    <h6 class="my-0" style="color:black;">@i . @orderItem.Product.Name &nbsp Qty - @orderItem.Quantity </h6>

                                    <small class="text-muted">@(orderItem.Product.Description.Length > 100 ? orderItem.Product.Description.Substring(0, 99) : orderItem.Product.Description)</small>
                                </div>
                                <span class="text-muted">Unit Price : $@orderItem.Product.Price -<strong> Total Price: @(orderItem.Quantity * orderItem.Product.Price)</strong></span>
                            </li>

                            i++;
                        }


                        <li class="list-group-item d-flex justify-content-between">
                            <strong>Grand Total (USD)</strong>
                            <strong>
                                @Model.Order.TotalAmount
                            </strong>
                        </li>
                    </ul>

                    <form class="card p-2">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Promo code">
                            <div class="input-group-append">
                                <button type="button" class="btn btn-secondary" style=" color:black;   background-color: deepskyblue;">Redeem</button>
                            </div>
                        </div>
                    </form>
                </div>

                <div class="col-md-6 order-md-1">
                    <h3 class="mb-3"> @Model.OrderedBy.Name Billing address</h3>
                    <div class="mb-3">
                        <label for="firstName">Full Name</label>
                        <input type="text" style="color:black;" class="form-control" id="fullname" placeholder="" value=" @Model.OrderedBy.Name" disabled>
                    </div>

                    <div class="mb-3">
                        <label for="email">Email </label>
                        <input type="email" style="color:black;" class="form-control" id="Email" value="@Model.OrderedBy.Email" disabled>

                    </div>

                    <div class="mb-3">
                        <label for="address">Address</label>
                        <input type="text" style="color:black;"  class="form-control" id="Address" value="@Model.OrderedBy.Address" disabled>

                    </div>

                    <div class="mb-3">
                        <label for="status"><strong>Status &nbsp;  &nbsp; ( Please Update status From Below DropDown )</strong></label>
                        <select name="Status" id="changeStatus">

                            @foreach (var avilableStatus in Model.AvilableStatuses)
                            {
                                var isSelectedStatus = avilableStatus == Model.Order.Status;

                                <option @(isSelectedStatus ? "selected" : string.Empty)>
                                    @avilableStatus
                                </option>
                            }
                        </select>

                    </div>
                    <br />  <br />  <br />  <br />  <br />
                </div>
            </div>
        </div>
    </section>


    <script>

        $("#changeStatus").change(function () {

        $.ajax({

                url: '@Url.Action("ChangeStatus","Order")', //'/Product/ProductTable',

                data: {
                    status: $("#changeStatus").val(),
                    ID : '@Model.Order.ID'
                }
            })
                .done(function (response) {
                    if (response.Success) {
                        swal("Done", "Order Has Been Updated", "success").then((value) => { window.location = '@Url.Action("Orders", "Admin")'; });;
                        //$("#actionContainer").html("");
                        //focusAction("tableContainer")

                    }
                    else
                    {
                        swal("Error", "Enable To Update  Order", "Warning");
                    }
                })
                .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                    alert("Fail");
                });
        });

    </script>
}


else
{
    <section class="flat-row main-shop shop-slidebar">
        <div class="container">


            <div class="row">
                <b> Order Details Not Avilable </b>


            </div>

        </div>

    </section>
}




@*<script>

            $('#changeStatus').click(function () {
                debugger;
            $.ajax({
                     type: "POST",
                    url:'@Url.Action("ChangeStatus","Order")', //'/Product/ProductTable',

                    data: {
                        status: $("#Status").val(),
                        ID : '@Model.Order.ID'
                    }
                })
                    .done(function (response) {
                        if (response.Success) {
                            swal("Done", "Your Order Has Been Placed", "success");

                        }
                        else
                        {
                            swal("Failed", " Enable To Place Your Order", "Warning");
                        }
                    })
                    .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("Fail");
                    });
            });

    </script>*@

Market.Web/Views/Order/_Index.cshtml
<section class="flat-row flat-iconbox">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="title-section">
                    <h2 class="title">
                        User Order's
                    </h2>
                </div><!-- /.title-section -->
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section><!-- /.flat-row -->



<div class="container">
    <div id="tableContainerOrder">
        @{
            Html.RenderAction("OrderTable");

            //Html.RenderAction("Create");
        }
    </div>
    <hr />
    <div id="actionContainer">

    </div>
</div>


<script>


        function focusAction(controlToFocus) {
            $('html, body').animate({
                scrollTop: $("#" + controlToFocus).offset().top - 100
            }, 1000);
        }



    </script>

Market.Web/Views/Order/_OrderList.cshtml
@model OrderViewModels


    
    
   <h3>Total Oders<span>( @Model.Pager.TotalItems )</span></h3>
        <form method="post">
            <div class="row" style="margin-top:10px">

                <div class="col-md-6">
                    <div class="form-group">
                        <input class="form-control" id="searchtxt" name="UserId" value="@Model.userID" placeholder="Search Oder's By His User Id !!" />
                    </div>
                </div>
                <div class="col-md-6">
                    <button type="button" id="searchBtn" class="btn btn-primary">Search</button>
                    <button type="button" id="resetBtn" class="btn btn-success ">Reset Search</button>
                
                </div>

            </div>
        </form>


        <div>
            <table id="OdersTable" class="table">
                <thead class="font-weight-bold">
                    <tr>
                        <th class="font-weight-bold"> User ID</th>
                        <th class="font-weight-bold"> Total Price</th>
                        <th class="font-weight-bold"> Status</th>
                        <th class="font-weight-bold">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model.Orders != null && Model.Orders.Count > 0)
                    {
                        foreach (var order in Model.Orders)
                        {
                    <tr>
                        <td>@order.UserID</td>
                        <td>
                            @order.TotalAmount
                        </td>
                        <td>@order.Status</td>
                        <td>
                            <button class="detailBtn" data-id="@order.ID">Details</button>
                        </td>
                        @*<td class="wrap-td">
                            <a class="detailBtn" data-id="@order.ID" href="@Url.Action("Details", "Order", new { ID = order.ID })">Details</a>
                        </td>*@
                    </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td class="text-danger" colspan="4">

                                No Product Found
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
            <div>
                @if (Model.Pager != null && Model.Pager.TotalPages > 1)
                {


                    if (Model.Pager.CurrentPage > 1)
                    {
                        <button class="pageButtons" data-pageNo="1"> First </button>
                        <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage - 1)"> Previous </button>
                    }
                    for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                    {
                        string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                        <button class=" @activeClass pageButtons" data-pageNo="@page"> @page </button>
                    }
                    if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                    {
                        <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage + 1)"> next </button>
                        <button class="pageButtons" data-pageNo="@Model.Pager.EndPage"> Last </button>
                    }

                }
            </div>
        </div>



<script>

    $(".pageButtons").click(function () {
        debugger;
        $.ajax({
            type: "GET",
            url: '@Url.Action("OrderTable", "Order")', //'/Product/ProductTable',
            data: {
                pageNo: $(this).attr("data-pageno"),
                userID: '@Model.userID',
                status:'@Model.status'
            }
        })
            .done(function (response) {
                $("#actionContainer").html("");
                focusAction("tableContainerOrder");
                $("#tableContainerOrder").html(response);
             
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });


        //function focusAction(controlToFocus) {
        //    $('html, body').animate({
        //        scrollTop: $("#" + controlToFocus).offset().top - 100
        //    }, 1000);
        //}

    $("#searchBtn").click(function ()
    {
        debugger;
        var seacrhvalue = $("#searchtxt").val();

        $.ajax({
            type: "GET",
            url: '@Url.Action("OrderTable", "Order")', //'/Product/ProductTable',
            data: { userID: seacrhvalue }
        })
            .done(function (response) {
                $("#tableContainerOrder").html(response);
                focusAction("tableContainerOrder");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

       $("#resetBtn").click(function () {
        var seacrhvalue = $("#searchtxt").val();

        $.ajax({
            type: "GET",
            url:  '@Url.Action("OrderTable", "Order")', //'/Product/ProductTable',

        })
            .done(function (response) {
                $("#tableContainerOrder").html(response);
                focusAction("tableContainerOrder");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

     
    $(".detailBtn").click(function () {
        debugger;
        $.ajax({
            type: "GET",
            url: '@Url.Action("Details","Order")', // '/Product/Edit',
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                focusAction("actionContainer");
                $("#actionContainer").html(response);

            
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

</script>