Market.Web/Controllers/CategoryController.cs
using Market.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Market.Services;
using Market.Web.ViewModels;
using System.Data.Entity;

namespace Market.Web.Controllers
{
    public class CategoryController : Controller
    {
        //CategorysServices categoryService = new CategorysServices(); // because we have Market Service class in which we are taking to Database
        #region Mainpage-Index-contain-CategoryTable-with-Action
        [HttpGet] //list of Category
        public ActionResult Index() // using for listing Caregory 
        {
         //   var categories = CategorysServices.Instance.GetAllCategories(); // Calling service layer User-define fu nction for taking category

            return PartialView("_Index"); //categories

        }
        #endregion

        #region category-table

        public ActionResult CategoryTable(string search, int? pageNO)
        {

            CategorySearchViewMOdel model = new CategorySearchViewMOdel();
            model.SearchTerm = search;

            pageNO = pageNO.HasValue ? pageNO.Value > 0 ? pageNO.Value : 1 : 1;

            var totalRecord = CategorysServices.Instance.GetCategoriesCount(search);

            model.Categories = CategorysServices.Instance.GetCategories(search, pageNO.Value);
            if (model.Categories != null)
            {
                int pageSize = int.Parse(ConfigurationService.Instance.GetConfiguration("ListingPageSize").Value);
                model.Pager = new Pager(totalRecord, pageNO, pageSize);
                return PartialView("_CategoryTable", model);
            }
            else
            {
                return HttpNotFound();
            }

        }
        #endregion

        #region Creation
        [HttpGet] // createing category
                public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [ValidateAntiForgeryToken()]
        [HttpPost]
        public ActionResult Create(NewCaregoryViewModel model) // taking value from view in category object 
        {
            if (ModelState.IsValid)
            {
                var NewCategory = new Category();
                NewCategory.Name = model.Name;
                NewCategory.Description = model.Description;
                NewCategory.ImageUrl = model.ImageUrl;
                NewCategory.IsFeatured = model.isFeatured;

                CategorysServices.Instance.saveCategory(NewCategory); // now passing Category value to USER-DEFINED Function which is created in Market category class. 

                return RedirectToAction("CategoryTable");
            }
            else
            {
                return new HttpStatusCodeResult(500);
            }
         
        }
        #endregion

        #region Updation
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            EditCategoryViewModel model = new EditCategoryViewModel();
            var category = CategorysServices.Instance.GetCategory(Id);
            model.ID = category.ID;
            model.Name = category.Name;
            model.Description = category.Description;
            model.ImageURL = category.ImageUrl;
            model.isFeatured = category.IsFeatured;


            return PartialView("_Edit",model);
        }

        [HttpPost]
        public ActionResult Edit(EditCategoryViewModel model)
        {
            var existingCategory = CategorysServices.Instance.GetCategory(model.ID);
            existingCategory.Name = model.Name;
            existingCategory.Description = model.Description;
            existingCategory.ImageUrl = model.ImageURL;
            existingCategory.IsFeatured = model.isFeatured;

            CategorysServices.Instance.updateCategory(existingCategory);

            return RedirectToAction("CategoryTable");
        }
        #endregion

        #region Deletion
        [HttpPost]
        public ActionResult Delete(int ID)
        {
            CategorysServices.Instance.DeleteCategory(ID);
            return RedirectToAction("CategoryTable");
        }
        #endregion
    }
}

Market.Web/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Market.Web.Controllers
{
    public class SharedController : Controller
    {
       //Image uploading 

        public JsonResult UploadImage()
        {
            JsonResult result = new JsonResult
            {
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };

            try
            {
                var file = Request.Files[0];

                var filename =Guid.NewGuid() + Path.GetExtension(file.FileName);

                var path = Path.Combine(Server.MapPath("~/Content/Images/"), filename);

                file.SaveAs(path);

                result.Data = new { Success = true, ImageURL = string.Format("/Content/Images/{0}",filename) };

                //  var newImage = new Image() { name = filename };

               
            }
            catch(Exception ex)
            {
                result.Data = new { success = false , Message = ex.Message  };
            }

            return result;
                      
        }
    }
}

Market.Web/Views/Category/_CategoryTable.cshtml
@model Market.Web.ViewModels.CategorySearchViewMOdel
@{
    ViewBag.Title = "CategoryTable";
}

<div>
    <br />
    <form method="post">
        @Html.AntiForgeryToken()
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">

                    @{string val = Model.SearchTerm != null ? val = Model.SearchTerm : Model.SearchTerm = null; }
                    @*@if (Model.SearchTerm != null)
                    {
                        string serch = Model.SearchTerm;
                        <input class="form-control" id="searchtxt" name=" Search" placeholder="Search Category Here !!" value="@serch" />

                    }
                    else
                    {
                        <input class="form-control" id="searchtxt" name=" Search" placeholder="Search Category Here !!" />

                    }*@

                    <input class="form-control" id="searchtxt" name=" Search" placeholder="Search Category Here !!" value="@val" />

                </div>
            </div>
            <div class="col-md-6">
                <button type="button" id="searchBtn" class="btn btn-primary">Search</button>
                <button type="button" id="resetBtn" class="btn btn-success ">Reset Search</button>
                <button type="button" id="newBtn" class="btn btn-warning">Create New Category</button>
            </div>

        </div>


    </form>
    </div>
    <div>
        <table class="table">
            <thead class="font-weight-bold">
                <tr>
                    <th class="font-weight-bold"> Category Name (@Model.Pager.TotalItems)</th>
                    <th class="font-weight-bold">Products</th>
                    <th class="font-weight-bold">IsFeatured</th>
                    <th class="font-weight-bold wrap-td">Actions</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Categories != null && Model.Categories.Count > 0)
                {
                    foreach (var category in Model.Categories)
                    {
                        <tr>
                            <td>@category.Name</td>
                            <td>
                                @category.Products.Count

                            </td>


                            <td>@category.IsFeatured</td>
                            <td>
                                <button class="editBtn" data-id="@category.ID">Edit</button>

                                <button class="deleteBtn" data-id="@category.ID">Delete</button>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr><td colspan="3" class="text-danger">No Category Found</td></tr>}


            </tbody>
        </table>

        <div>
            @if (Model.Pager != null && Model.Pager.TotalPages > 1)
            {
                if (Model.Pager.CurrentPage > 1)
                {
                    <button class="pageButtons" data-pageNo="1"> First </button>
                    <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage - 1)"> < </button>
                }


                for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
                {
                    string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                    <button class=" @activeClass pageButtons" data-pageNo="@page"> @page </button>
                }


                if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
                {
                    <button class="pageButtons" data-pageNo="@(Model.Pager.CurrentPage + 1)"> > </button>
                    <button class="pageButtons" data-pageNo="@Model.Pager.EndPage"> Last </button>
                }
            }

        </div>
    </div>



    <script>


    $(".pageButtons").click(function () {
        $.ajax({
            type: "GET",
            url: '@Url.Action("CategoryTable", "Category")', //'/Product/ProductTable',
            data: {
                pageNo: $(this).attr("data-pageNo"),
                search: '@Model.SearchTerm'


            }
        })
            .done(function (response) {
                $("#actionContainer").html("");
                focusAction("tableContainer");
                $("#tableContainer").html(response);
            
           


            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });



    $("#searchBtn").click(function () {
        var seacrhvalue = $("#searchtxt").val();

        $.ajax({
            type: "GET",
            url: '@Url.Action("CategoryTable", "Category")', //'/Product/ProductTable',
            data: { search: seacrhvalue }
        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#resetBtn").click(function () {

        $.ajax({
            type: "GET",
            url: '@Url.Action("CategoryTable", "Category")', // '/Product/ProductTable',

        })
            .done(function (response) {
                $("#tableContainer").html(response);
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });


    $("#newBtn").click(function () {

        $.ajax({
            type: "GET",
            url :'@Url.Action("Create","Category")',
        })
            .done(function (response) {
                focusAction("actionContainer");
                $("#actionContainer").html(response);
                
            })
            .fail(function (XMLHttpResuest,textStatus,errorThrown) {
                alert("fail")
            })
    });




    $(".editBtn").click(function () {

        $.ajax({
            type: "GET",
            url: '@Url.Action("Edit", "Category")', /*'/Category/Edit',*/
            data: {
                ID: $(this).attr('data-id')
            }
        })
            .done(function (response) {
                focusAction("actionContainer")
                $("#actionContainer").html(response);
                
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });


    //$(".deleteBtn").click(function () {
    //    var dlt = confirm("Are you sure you want to delete this category?");
    //    debugger;
    //    if(dlt == true)
    //    {
    //        $.ajax({
    //            type: "POST",
    //            url: '/Category/Delete',
    //            data: { ID: $(this).attr('data-id') }
    //        })
    //            .done(function (response) {
    //                $("#tableContainer").html(response);

    //            })
    //            .fail(function (XMLHttpRequest, textstatus, errorThrown) {
    //                alert("Fail")
    //            })
    //    }

    //});

    $(".deleteBtn").click(function () {
        swal({
            title: "Confirm?",
            text: "Are you sure you want to delete this category?",
            icon: "warning",
            buttons: true,
            dangerMode: true,
        })
            .then((willDelete) => {
                if (willDelete) {

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("Delete", "Category")', /*'/Category/Delete',*/
                        data: { ID: $(this).attr('data-id') }
                    })
                        .done(function (response) {
                            $("#tableContainer").html(response);
                            $("#actionContainer").html("");
                            focusAction("tableContainer");

                        })
                        .fail(function (XMLHttpRequest, textstatus, errorThrown) {
                            alert("Fail")
                        })

                    swal("Record deleted Successfully", {
                        icon: "success",
                    });
                }
            });
    });




    </script>

Market.Web/Views/Category/_Create.cshtml
@{
    ViewBag.Title = "Create Category";

}

<h2>Create Category</h2>

<form id="createCategory">
    @Html.AntiForgeryToken()
    <div class="row">

        <div class="col-md-8">
            <div class="form-group">
                <lable class="form-group">Name<span class="text-danger">*</span></lable>
                <input class="form-control" name="Name" />

            </div>


            <div class="form-group">

                <lable>Description</lable>
                <input class="form-control" name="Description" />
            </div>

            <div class="form-group">
                <lable>Image</lable>
                <input id="ImageUrl" type="hidden" name="ImageUrl" />
                <input id="imageUpload" name="Image" type="file" accept=".png,.jpg" />
                <br />
            </div>




            <div class="form-group">
                <lable>Is Featured?</lable>
                <div class="input-group">
                    <div class="radio form-control">
                        <label><input type="radio" name="isfeatured" value="true" /> true</label>
                    </div>
                    <div class="radio form-control">
                        <label><input type="radio" name="isfeatured" value="false" /> False</label>
                    </div>
                </div>
                @*<input class="form-control" type="radio" name="isfeatured" value="true" /> true
                    <input class="form-control" type="radio" name="isfeatured" value="false" /> False*@


            </div>


            <button id="saveBtn" type="button"> Save Category</button>
            <button id="cancleBtn" type="button">Cancle</button>
        </div>
        <div class="col-md-4">

            <div class="thumb">
                <img @*src="@imageurl" class="img-thumbnail img-fluid*@ id="Categoryimage" />
            </div>
        </div>

    </div>

</form>

<script>
    $("#cancleBtn").click(function () {

        $("#actionContainer").html("");
        focusAction("tableContainer");

        });

    $('#imageUpload').change(function () {
        debugger;

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }

        $.ajax({
            type: "POST",
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {
                debugger;
                console.log(response)
                if (response.Success) {
                    $('#ImageUrl').val(response.ImageURL)
                    $('#Categoryimage').attr("src", response.ImageURL)
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });


    });

    $("#saveBtn").click(function () {
        if ($("#createCategory").valid()) {

            $.ajax({
            type: "POST",
            url:  '@Url.Action("Create", "Category")', //'/Category/Create',
            data: $("#createCategory").serialize()
        })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#actionContainer").html("");
                focusAction("tableContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                swal({
                    title: "Warning..!!",
                    text: "Internal Server Error",
                    icon: "warning",
                    buttons: true,
                    dangerMode: true,
                });
            });



        }
        else {
            swal({
                title: " JQury Warning..!!",
                text: "Please enter all Required fields",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            });
        }

    });






    $("#createCategory").validate({
            // Specify validation rules
            rules: {
                // The key name on the left side is the name attribute
                // of an input field. Validation rules are defined
                // on the right side
                Name: { required: true , minlength : 5, maxlength :50 },
                Description: { maxlength: 500 }
            },
            // Specify validation error messages
            messages: {
                Name: { required: 'Name is Required', minlength: 'Minimum length is 5', maxlength: 'Maximun length is 50' },
                Description: {  maxlength: 'Maximun length is 500' }
                  },

        });

</script>

Market.Web/Views/Category/_Edit.cshtml
@*This is Category Create View*@

@model Market.Web.ViewModels.EditCategoryViewModel
@*Add this line because we are getting Caterory object from edit get method*@

@{
    
    ViewBag.Title = "Edit";
    var trueChecked = Model.isFeatured ? "checked" : string.Empty;
    var falseChecked = !Model.isFeatured ? "checked" : string.Empty;
    var imageurl = !string.IsNullOrEmpty(Model.ImageURL) ? Model.ImageURL : "/Content/Images/system/placeholder.png";
}

<h2>Edit Category</h2>


<form id="editCategory">

    <input type="hidden" name="ID" value="@Model.ID" />

    <div class="row">

        <div class="col-md-8">
            <div class="form-group">
                <lable class="form-group">Name</lable>
                <input class="form-control" name="Name" value="@Model.Name" />
            </div>

            <div class="form-group">
                <lable>Description</lable>
                <input class="form-control" name="Description" value="@Model.Description" />
            </div>

            <div class="form-group">
                <lable>Image</lable>
                <input id="ImageUrl" type="hidden" name="ImageUrl" value="@Model.ImageURL" />
                <input class="form-control" id="imageUpload" name="Image" type="file" accept=".png,.jpg" />
                <br />
            </div>

            <div class="form-group">
                <lable>Is Featured?</lable>
                <div class="input-group">
                    <div class="radio form-control">
                        <label>       <input type="radio" name="isfeatured" value="true" @trueChecked /> true</label>
                    </div>
                    <div class="radio form-control">
                        <label>   <input type="radio" name="isfeatured" value="false" @falseChecked /> False</label>
                    </div>
                </div>
                <button id="updateBtn" type="button"> Update Category</button>
                <button id="cancleBtn" type="button"> Cancle</button>
            </div>

        </div>
        <div class="col-md-4">
            <div class="thumb">
                <img id="Categoryimage" src="@imageurl" class="img-thumbnail  img-fluid " />
            </div>
        </div>

    </div>

</form>
<script>
    $("#cancleBtn").click(function () {
        $("#actionContainer").html("");
        focusAction("tableContainer");
    });
    $('#imageUpload').change(function () {

        var element = this;
        var formData = new FormData();
        var totalFiles = element.files.length;
        for (var i = 0; i < totalFiles; i++) {
            var file = element.files[i];
            formData.append("Photo", file);
        }
        $.ajax({
            type: "POST",
            url: '@Url.Action("UploadImage", "Shared")', //'/Shared/UploadImage',
            data: formData,
            dataType: 'json',
            contentType: false,
            processData: false
        })
            .done(function (response) {

                console.log(response)
                if (response.Success) {
                    $('#ImageUrl').val(response.ImageURL)
                    $('#Categoryimage').attr("src", response.ImageURL)
                }
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });

    $("#updateBtn").click(function () {
        debugger;
        $.ajax({
            type: "POST",
            url: '@Url.Action("Edit","Category")', //'/Category/Edit',
            data: $('#editCategory').serialize()
        })
            .done(function (response) {
                $("#tableContainer").html(response);
                $("#actionContainer").html("");
                focusAction("tableContainer");
            })
            .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                alert("Fail");
            });
    });



</script>

Market.Web/Views/Category/_Index.cshtml
@model List<Market.Entities.Category>

@{
    ViewBag.Title = "caretory Index";
}
<section class="flat-row flat-iconbox">

    <div class="row">
        <div class="col-md-12">
            <div class="title-section">
                <h2 class="title">
                    Categories
                </h2>
            </div><!-- /.title-section -->
        </div><!-- /.col-md-12 -->
    </div><!-- /.row -->

</section><!-- /.flat-row -->


<div class="container">
    <div id="tableContainer">
        @Html.AntiForgeryToken()
        @{
            Html.RenderAction("CategoryTable");

            //Html.RenderAction("Create");
        }
    </div>
    <hr />
    <div id="actionContainer">

    </div>
</div>
<script>
        function focusAction(controlToFocus) {
            $('html, body').animate({
                scrollTop: $("#" + controlToFocus).offset().top - 100
            }, 1000);
        }
    </script>
 