Market.Web/ViewModels/ShopViewModels.cs
using Market.Entities;
using Market.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Market.Web.ViewModels
{
    public class ShopViewModel
    {
        public List<Product> Products { get; set; }
        public List<Category> FeaturedCategories { get; set; }
        public int MinimumPrice { get; set; }
        public int MaximumPrice { get; set; }
        public int? soryby { get;  set; }
        public int? CategoryID { get; set; }


        public Pager Pager { get; set; }
        public string SearchTerm { get;  set; }
    }
    public class CheckoutViewModel
    {
        public List<Product> CartProducts { get; set; }
        public List<int> CartProductIDs { get; set; }
        public MarketUser User { get; set; }
    }
    public class FilterProductViewModel
    {
        public List<Product> Products { get; set; }
         
        public Pager Pager { get; set; }
        public int? CategoryID { get;  set; }
        public int? soryby { get;  set; }
        public object SearchTerm { get;  set; }
    }
}

Market.Web/Controllers/ProductController.cs
using Market.Entities;
using Market.Services;
using Market.Web.ViewModels;
using System.Linq;
using System.Web.Mvc;

namespace Market.Web.Controllers
{
    public class ProductController : Controller
    {

        //ProductsService productsService = new ProductsService();
       // CategorysServices CategorysServices = new CategorysServices();

        public ActionResult Index()
        {

            return PartialView();
        }

        public ActionResult ProductTable(string search, int? pageNo)
        {

            ProductSearchViewModel model = new ProductSearchViewModel();

            model.SearchTerm = search;
            pageNo = pageNo.HasValue ? pageNo.Value>0 ? pageNo.Value : 1 :1;
            //            simmilar to above single line
            //            if (pageNo.HasValue)
            //            { if(pageNo.Value>0)
            //                {
            //                    model.pageNo = pageNo.Value;
            //                }
            //                else
            //                {
            //                    model.pageNo = 1
            //;                }
            //            }
            //            else { model.pageNo = 1; }

            // model.Products = ProductsService.Instance.GetProducts(model.pageNo);

            var totalRecord = ProductsService.Instance.GetProductsCount(search);
            model.Products = ProductsService.Instance.GetProducts(search, pageNo.Value);

            if (model.Products != null)
            {
                int pageSize = ConfigurationService.Instance.PagesizeConfiguration();
                model.Pager = new Pager(totalRecord, pageNo, pageSize);
                return PartialView("ProductTable", model);
            }
            else
            {
                return HttpNotFound();
            }

            //   products = products.Where(p => p.Name == search).ToList();
            //if (!string.IsNullOrEmpty(search))
            //{
            //    model.SearchTerm = search;
            //   model.Products = model.Products.Where(p => p.Name != null && p.Name.ToLower().Contains(search.ToLower())).ToList();
            //}
            // return PartialView(model);
        }

        //Create 
        [HttpGet]
        public ActionResult Create()
        {
            NewProductViewModel model = new NewProductViewModel();
            model.AvailableCategories= CategorysServices.Instance.GetAllCategories();

            return PartialView(model);
        }


        [HttpPost]
        public ActionResult Create(NewProductViewModel model) // Creating new Product
        {
            if (ModelState.IsValid)
            {
                var newProduct = new Product()
                {
                    Name = model.Name,
                    Description = model.Description,
                    Price = model.Price,
                    ImageUrl = model.ImageURL,
                    //CategoryID=model.CategoryID
                    Category = CategorysServices.Instance.GetCategory(model.CategoryID)
                };
                ProductsService.Instance.saveProduct(newProduct);
                return RedirectToAction("ProductTable");
            }
            else
            {
                return PartialView(model);
            }
        
        }
        //Edit
        [HttpGet]
        public ActionResult Edit(int ID)
        {
            EditProductModel model = new EditProductModel();

            var product = ProductsService.Instance.GetProduct(ID);
            model.ID = product.ID;
            model.Name = product.Name;
            model.Description = product.Description;
            model.Price = product.Price;
            model.CategoryID = product.Category != null ? product.Category.ID : 0;
            model.ImageUrl = product.ImageUrl;

            model.AvailableCategories = CategorysServices.Instance.GetAllCategories();


            return PartialView(model);
        }

        [HttpPost]
        public ActionResult Edit(EditProductModel model) // taking value from view in Product object 
        {
            var existingProduct = ProductsService.Instance.GetProduct(model.ID);
            existingProduct.Name = model.Name;
            existingProduct.Description = model.Description;
            existingProduct.Price = model.Price;
         

            existingProduct.Category = null; //mark it null. Because the referncy key is changed below
            existingProduct.CategoryID = model.CategoryID;

            // dont update imageURL if its empty
            if (!string.IsNullOrEmpty(model.ImageUrl))
            {
                existingProduct.ImageUrl = model.ImageUrl;
            }

            //ProductsService.Instance.UpdateProduct(existingProduct);



            ProductsService.Instance.updateProduct(existingProduct); // now passing Product value to USER-DEFINED Function which is created in Market Product class. 
            return RedirectToAction("ProductTable");
        }
        [HttpPost]
        public ActionResult Delete(int ID) // taking value from view in Product object 
        {
            ProductsService.Instance.DeleteProduct(ID); // now passing Product value to USER-DEFINED Function which is created in Market Product class. 
            return RedirectToAction("ProductTable");
        }


        [HttpGet]
        public ActionResult ProductDetails(int ID )
        {
            ProductViewModel model = new ProductViewModel();

            model.Product = ProductsService.Instance.GetProduct(ID);

            return View(model);
        }

    }

}

Market.Web/Controllers/ShopController.cs
using Market.Entities;
using Market.Services;
using Market.Web.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;



namespace Market.Web.Controllers
{

    public class ShopController : Controller
    {
        // GET: Shop







        private MarketSignInManager _signInManager;
        private MarketUserManager _userManager;


        public MarketSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<MarketSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }

        public MarketUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<MarketUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }








     
        public ActionResult Index(string searchTerm, int? minimumPrice, int? maximumPrice, int? CategoryID, int? sortBy, int? pageNo)
        {
            ShopViewModel model = new ShopViewModel();


            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.soryby = sortBy;
            model.CategoryID = CategoryID;
            model.SearchTerm = searchTerm;



            model.FeaturedCategories = CategorysServices.Instance.GetFeaturedCategories();

            model.MaximumPrice = ProductsService.Instance.GetMaximumPrice();

            model.Products = ProductsService.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, CategoryID, sortBy, pageNo.Value, 9);



            int totalCount = ProductsService.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, CategoryID, sortBy);
            model.Pager = new Pager(totalCount, pageNo);

            return View(model);
        }

        [OutputCache(Duration = 60)]
         public ActionResult FilterProducts(string searchTerm, int? minimumPrice, int? maximumPrice, int? CategoryID, int? sortBy, int? pageNo)
        {
            FilterProductViewModel model = new FilterProductViewModel();

            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo.Value : 1 : 1;
            model.soryby = sortBy;
            model.CategoryID = CategoryID;

            model.SearchTerm = searchTerm;

            int totalCount = ProductsService.Instance.SearchProductsCount(searchTerm, minimumPrice, maximumPrice, CategoryID, sortBy);
            model.Products = ProductsService.Instance.SearchProducts(searchTerm, minimumPrice, maximumPrice, CategoryID, sortBy, pageNo.Value, 9);

            model.Pager = new Pager(totalCount, pageNo);

            return PartialView(model);
        }













        [Authorize]
        public ActionResult Checkout() // taking caart value from cookies and providing Amount
        {
            CheckoutViewModel model = new CheckoutViewModel();

            var cartProductsCookie = Request.Cookies["cartProducts"];
            //ProductsService productsService = new ProductsService();
            if (cartProductsCookie != null && !string.IsNullOrEmpty(cartProductsCookie.Value))
            {
                //var productIDs = cartProductsCookie.Value;
                //var ids = productIDs.Split('-');
                //List<int> pIds = ids.Select(x => int.Parse(x)).ToList();]
                //Above 3  line in single line 

                model.CartProductIDs = cartProductsCookie.Value.Split('-').Select(x => int.Parse(x)).ToList();

                model.CartProducts = ProductsService.Instance.GetProducts(model.CartProductIDs);

                model.User = UserManager.FindById(User.Identity.GetUserId());

            }

            return View(model);
        }

        public JsonResult PlaceOrder(string productIDs)
        {

            JsonResult result = new JsonResult();
            result.JsonRequestBehavior = JsonRequestBehavior.AllowGet;
             

            if (!string.IsNullOrEmpty(productIDs))
            {

                var productsQuantities = productIDs.Split('-').Select(x => int.Parse(x)).ToList();



                //var PIDs = productIDs.Split(new char[] { '-' }).Select(x => int.Parse(x)).Distinct().ToList();

                var BoughtProducts = ProductsService.Instance.GetProducts(productsQuantities.Distinct().ToList());   //here we get Bought Product Ids





                Order newOrder = new Order();
                newOrder.UserID = User.Identity.GetUserId();
                newOrder.OrdererAt = DateTime.Now;
                newOrder.Status = "Pending";

                //Total amount nikalne ke liye hamko ... product ki price and ouski Quantities ka Product krna hoga 
                //Product ki price Bought Products  me product ki id ke base pr ouska price lehenge
                //and quantity nikalne ke liye ham.. productsQuantities jo productIDs hai ounka ek ek krke Count nikalhenge
                // and me Quantity and Product ka multiply kr dehenge  

                newOrder.TotalAmount = BoughtProducts  //jo product bought kiye hai
                                        .Sum(product => product.Price   //ouske price ka Sum pick kro
                                        * productsQuantities            //Lekin Product ki Quantities 
                                        .Where(productID => productID == product.ID) // jo productQuantity me product Id hai ousko BoughtProduct Id se compare kro
                                        .Count());                     //Compare krne me bad.. id ka count nikalo.. nd ousko product Quantity Banalo


                newOrder.OrderItems = new List<OrderItem>();
                newOrder.OrderItems.AddRange(BoughtProducts.Select(x => new OrderItem() { ProductID = x.ID ,Quantity =productsQuantities.Where(productID => productID ==x.ID).Count() }));

                var rowsEffected = ShopService.Instance.SaveOrder(newOrder);

                result.Data = new { Success = true, Rows = rowsEffected };
            }
            else
            {
                result.Data = new { Success = false };
            }

            return result;
        }
    }
}

Market.Web/Views/Shop/FilterProducts.cshtml
@model FilterProductViewModel

@{
    var Defaultimageurl = "/Content/Images/system/placeholder.png";
}
<div class="filter-shop clearfix">
    <p class="showing-product float-right">
        Showing @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + 1)– @(((Model.Pager.CurrentPage - 1) * Model.Pager.PageSize) + (Model.Products.Count < Model.Pager.PageSize ? Model.Products.Count : Model.Pager.PageSize)) of @Model.Pager.TotalItems Products
    </p>
</div><!-- /.filte-shop -->
<div class="product-content product-threecolumn product-slidebar clearfix">
    <ul class="product style2 sd1">

        @foreach (var product in Model.Products)
        {

            var imageURL = string.IsNullOrEmpty(product.ImageUrl) ? Defaultimageurl : product.ImageUrl;
            <li class="product-item">
                <div class="product-thumb clearfix">
                    <a href="@Url.Action("ProductDetails", "Product",new { ID = product.ID  } )">
                        <img src="@imageURL" alt="image" style="height:250px; width:250px">
                    </a>
                </div>
                <div class="product-info clearfix">
                    <span class="product-title"><br />@product.Name</span>
                    <div class="price">
                        <ins>
                            <span class="amount">$@product.Price</span>
                        </ins>
                    </div>
                </div>
                <div class="add-to-cart text-center">
                    <a class="productAddToCart" data-id="@product.ID">ADD TO CART</a>
                </div>
                <a href="#" class="like"><i class="fa fa-heart-o"></i></a>
            </li>
        }


    </ul><!-- /.product -->
</div><!-- /.product-content -->



@if (Model.Pager != null && Model.Pager.TotalPages > 1)
{
    <div class="product-pagination text-center clearfix">




        <ul class="flat-pagination">

            @if (Model.Pager.CurrentPage > 1)
            {
                <li class="prev">

                    <a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = Model.Pager.CurrentPage - 1, sortby = Model.soryby, categoryID = Model.CategoryID })" class="pageDataLink"><i class="fa fa-angle-left"></i></a>

                    @*<a href="@Url.Action("Index","Shop", new { pageNo = 1})">1</a>*@

                </li>
            }


            @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <li class="@activeClass"><a data-href="@Url.Action("FilterProducts","Shop", new { pageNo = page,sortby = Model.soryby, categoryID = Model.CategoryID})" class="pageDataLink">@page</a></li>

            }

            @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {

                <li>
                    <a data-href="@Url.Action("FilterProducts", "Shop", new { pageNo = Model.Pager.CurrentPage + 1 ,sortby = Model.soryby, categoryID = Model.CategoryID }) " class="pageDataLink"> <i class="fa fa-angle-right"></i> </a>
                </li>

                @*<li> <a href="@Url.Action("Index", "Shop", new { pageNo = Model.Pager.EndPage }) "><i class="fa fa-angle-double-right"> </a></li>*@

            }


        </ul><!-- /.flat-pagination -->
    </div>

 }

<input type="hidden" id="searchTerm" value="@Model.SearchTerm" />

<input type="hidden" id="sortby" value="@Model.soryby" />

<input type="hidden" id="categoryID" value="@Model.CategoryID" />



<script>
      $(".pageDataLink").click(function () {
        debugger;
          var url = $(this).attr("data-href");

        if (url != "" || url != undefined) {
            GetData(url);
        }
    });






    var products=[];
    $(".productAddToCart").click(function () {
   

        var existingCookieData = $.cookie('cartProducts');

        if (existingCookieData != undefined && existingCookieData != "" && existingCookieData != null)
        {
            products = existingCookieData.split('-');
        }
        else
        {
            products = [];
        }

        var productID = $(this).attr('data-id');

        products.push(productID);
        $.cookie('cartProducts', products.join('-'), { path: '/' });

        updateCartProductsIcon();

        swal("Done", "Product Added To Cart!", "success");

    });


</script>

Market.Web/Views/Shop/Index.cshtml
@using Market.Web.Code
@model ShopViewModel

@{
    var Defaultimageurl = "/Content/Images/system/placeholder.png";
}
<!-- Page title -->
<div class="page-title parallax parallax1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-title-heading">
                    <h1 class="title">Shop</h1>
                </div><!-- /.page-title-heading -->
                <div class="breadcrumbs">
                    <ul>
                        <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                        <li><a href="@Url.Action("Index", "Shop")">Shop</a></li>

                    </ul>
                </div><!-- /.breadcrumbs -->
            </div><!-- /.col-md-12 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.page-title -->

<section class="flat-row main-shop shop-slidebar">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <div class="sidebar slidebar-shop">
                    <div class="widget widget-search">
                        <form role="search" method="get" class="search-form" action="@Url.Action("Index", "Shop")">
                            <label>
                                <input type="search" class="search-field" placeholder="Search …" value="" name="searchTerm">
                            </label>
                            <input type="submit" class="search-submit" value="Search">
                        </form>
                    </div><!-- /.widget-search -->
                    <div class="widget widget-sort-by">
                        <h5 class="widget-title">
                            Sort By
                        </h5>
                        <ul>
                            <li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEmuns.Default })" class="dataLink @(Model.soryby.HasValue ? Model.soryby.Value == (int)SortByEmuns.Default ? "active" : string.Empty : string.Empty)">Default -Newness</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEmuns.Popularity })" class="dataLink @(Model.soryby.HasValue ? Model.soryby.Value == (int)SortByEmuns.Popularity ? "active" : string.Empty : string.Empty)">Popularity</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEmuns.PriceLowToHigh })" class="dataLink @(Model.soryby.HasValue ? Model.soryby.Value == (int)SortByEmuns.PriceLowToHigh ? "active" : string.Empty : string.Empty)">Price: low to high</a></li>
                            <li><a data-href="@Url.Action("FilterProducts", "Shop", new { sortBy = (int)SortByEmuns.PriceHighToLow })" class="dataLink @(Model.soryby.HasValue ? Model.soryby.Value == (int)SortByEmuns.PriceHighToLow ? "active" : string.Empty : string.Empty)">Price: high to low</a></li>
                        </ul>
                    </div><!-- /.widget-sort-by -->

                    <div class="widget widget-price">
                        <h5 class="widget-title">Filter by price</h5>

                        <div class="price-filter">
                            <div id="slide-range"></div>
                            <p class="amount">
                                Price: <input type="text" id="amount" disabled="">
                            </p>
                        </div>
                    </div>
                    <div class="widget widget_tag">
                        <h5 class="widget-title">
                            Featured Products
                        </h5>
                        <div class="tag-list">
                            @foreach (var category in Model.FeaturedCategories)
                            {
                                <a data-href="@Url.Action("FilterProducts", "Shop", new { categoryID = category.ID })" class="dataLink @(Model.CategoryID.HasValue && Model.CategoryID.Value == category.ID ? "active": string.Empty)"> @category.Name</a>
                            }


                        </div>
                    </div><!-- /.widget -->
                    <a data-href="@Url.Action("FilterProducts","Shop")" class="dataLink btn btn-secondary">Reset Filters </a>
                </div><!-- /.sidebar -->
            </div><!-- /.col-md-3 -->

            <div class="col-md-9">
                <div id="ProductsDiv">
                    @{
                        var filterProductViewModel = new FilterProductViewModel();
                        filterProductViewModel.Products = Model.Products;
                        filterProductViewModel.Pager = Model.Pager;
                        filterProductViewModel.CategoryID = Model.CategoryID;
                        filterProductViewModel.soryby = Model.soryby;


                        Html.RenderPartial("FilterProducts", filterProductViewModel);

                    }
                </div>

                @*<div class="product-content product-threecolumn product-slidebar clearfix">
                        <ul class="product style2 sd1">

                            @foreach (var product in Model.Products)
                            {

                                var imageURL = string.IsNullOrEmpty(product.ImageUrl) ? Defaultimageurl : product.ImageUrl;
                                <li class="product-item">
                                    <div class="product-thumb clearfix">
                                        <a href="@Url.Action("ProductDetails", "Product",new { ID = product.ID  } )">
                                            <img src="@imageURL" alt="image" style="height:250px; width:250px">
                                        </a>
                                    </div>
                                    <div class="product-info clearfix">
                                        <span class="product-title"><br />@product.Name</span>
                                        <div class="price">
                                            <ins>
                                                <span class="amount">$@product.Price</span>
                                            </ins>
                                        </div>
                                    </div>
                                    <div class="add-to-cart text-center">
                                        <a href="#">ADD TO CART</a>
                                    </div>
                                    <a href="#" class="like"><i class="fa fa-heart-o"></i></a>
                                </li>
                            }


                        </ul><!-- /.product -->
                    </div><!-- /.product-content -->
                    <div class="product-pagination text-center clearfix">
                        <ul class="flat-pagination">
                            <li class="prev">
                                <a href="#"><i class="fa fa-angle-left"></i></a>
                            </li>
                            <li><a href="#">1</a></li>
                            <li class="active"><a href="#" title="">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#"><i class="fa fa-angle-right"></i></a></li>
                        </ul><!-- /.flat-pagination -->
                    </div>*@
            </div><!-- /.col-md-9 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</section><!-- /.flat-row -->


<script>

    var callTimeout;


    var priceSlider = $("#slide-range").slider({
            range: true,
            min: 0,
            max: @Model.MaximumPrice,
            values: [0, @Model.MaximumPrice],

            slide: function (event, ui) {

                $("#amount").val("$" + ui.values[0] + ".00" + " - " + "$" + ui.values[1] + ".00");
                clearTimeout(callTimeout);
                callTimeout = setTimeout(PriceRangeChange,500)


            }
    });



    $(".dataLink").click(function () {
        debugger;
        var url = $(this).attr("data-href");

        if (url != "" || url != undefined) {
            GetData(url);
        }
    });



    function GetData(durl)
    {
        debugger;
        console.log("Get Data Called");
        $.ajax
            ({
              type: "POST",
              url: durl,  //'Url.Action("FilterProducts", "Shop")', //'/Category/Edit',
             data:
               {
                 minimumPrice: priceSlider.slider("values",0),
                 maximumPrice: priceSlider.slider("values", 1)
               }
            })
            .done
            (
            function (response)
                {
                $("#ProductsDiv").html(response);
                }
            )
            .fail
            (function (XMLHttpRequest, textStatus, errorThrown)
            {
                alert("Fail");
            }
            );

    }


      function PriceRangeChange()
    {

        console.log("Get Data Called");
        $.ajax
            (
            {
              type: "POST",
             url: '@Url.Action("FilterProducts", "Shop")', //'/Category/Edit',
             data:
             {
             
                 searchTerm: $("#searchTerm").val(),
                 sortBy: $("#sortby").val(),
                 CategoryID: $("#categoryID").val(),
                 minimumPrice: priceSlider.slider("values",0),
                 maximumPrice: priceSlider.slider("values", 1)
                  }
            }
            )
            .done
            (
            function (response)
                {
                $("#ProductsDiv").html(response);
                }
            )
            .fail
            (function (XMLHttpRequest, textStatus, errorThrown)
            {
                alert("Fail");
            }
            );

    }


</script>